version: '3.3'
services: 
  user_service:
    env_file:
      -  .env
    container_name: $USER_SERVICE_NAME
    build: .
    ports:
      - $USER_SERVICE_EXPOSE_PORT:$USER_SERVICE_PORT
    expose:
      - $USER_SERVICE_EXPOSE_PORT
    environment:
      PORT: $USER_SERVICE_PORT
      MONGO_URI: $MONGO_URI
      MEETINGS_SERVICE_PORT: $MEETINGS_SERVICE_PORT
      MEETINGS_SERVICE_SAVE_PATH: $MEETINGS_SERVICE_SAVE_PATH
      MEETINGS_SERVICE_MY_INTERVIEWS_PATH: $MEETINGS_SERVICE_MY_INTERVIEWS_PATH
      MEETINGS_SERVICE_INTERVIEW_PATH: $MEETINGS_SERVICE_INTERVIEW_PATH
      MEETINGS_SERVICE_INTERVIEW_TOKEN: $MEETINGS_SERVICE_INTERVIEW_TOKEN
      COMPILER_SERVICE_URL: $COMPILER_SERVICE_URL
      COMPILER_SERVICE_PATH: $COMPILER_SERVICE_PATH
      CONVERTER_SERVICE_URL: $CONVERTER_SERVICE_URL
      CONVERTER_SERVICE_IMAGE_PATH: $CONVERTER_SERVICE_IMAGE_PATH
      DEF_PASSWORD: $DEF_PASSWORD
    depends_on:
      - mongo
    restart: always
 
  mongo:
    env_file:
      -  .env
    image: mongo:4.4.6
    container_name: $MONGO_DB_NAME
    ports:
      - $MONGO_DB_EXPOSE_PORT:$MONGO_DB_PORT
    environment:
      MONGO_INITDB_DATABASE: $MONGO_INITDB_DATABASE
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
      MONGO_DB_PORT: $MONGO_DB_PORT
    command: $MONGO_DB_COMMAND
    volumes:
      - $MONGO_DB_VOLUMNES
    restart: always
